variables:
  POSTGRES_DB: nigirifalls_db
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev

stages:
  - test
  - deploy

Code quality check: 
  stage: test
  image: python:latest
  services:
    - postgres
  script: 
    - bash ./gitlab_tests.sh