variables:
  POSTGRES_DB: nigirifalls_db
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev

stages:
  - test

Code quality check: 
  stage: test
  image: python:latest
  services:
    - postgres
  script: 
    - bash ./gitlab_tests.sh
    
Deploy to Heroku:
  stage: deploy
  image: ruby:latest
  only:
    refs:
      - master
  script:
    - bash ./gitlab_deploy.sh