image: python:latest

services:
  - mysql:latest

stages:
  - build
  - test
  - deploy
  
variables: 
  MYSQL_DATABASE: dev
  MYSQL_ROOT_PASSWORD: dev
  Host: mysql
  User: notroot
  Password: notrootdev
  Database: sushidb
  
cache:
  paths:
  - ~/.cache/pip/

Build:
  stage: build
  script: bash ./gitlab_build.sh
  
Code quality: 
  stage: test 
  script: 
    - bash ./gitlab_tests.sh
    - python3 ./demo/manage.py test -k
  
Deploy:
  stage: deploy
  script: bash ./gitlab_deploygitlab_deploy.sh
  
  
