image: python:latest

services:
  - mysql:latest

stages:
  - test
  - deploy
  
variables: 
  MYSQL_DATABASE: nigirifalls_db
  MYSQL_ROOT_PASSWORD: de

Code quality: 
  stage: test 
  script: 
    - bash ./gitlab_tests.sh