image: python:latest

services:
  - mariadb:latest
  
variables:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: nigirifalls_db
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev

stages:
  - test
  - deploy

Code quality: 
  stage: test 
  script: 
    - bash ./gitlab_tests.sh