image: alpine:latest

services:
  - mysql:latest
  command: --default-authentication-plugin=mysql_native_password

stages:
  - stage
  - test
  - deploy
  
variables: 
  MYSQL_DATABASE: nigirifalls_db
  MYSQL_ROOT_PASSWORD: root
  DB_HOST: mysql
  DB_USERNAME: root

Code quality: 
  stage: test 
  script: 
    - bash ./gitlab_tests.sh