variables:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: nigirifalls_db
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev

stages:
  - test
  - deploy

Code quality check: 
  stage: test
  image: python:latest
  services:
    - mariadb:latest
  script: 
    - bash ./gitlab_tests.sh
    
Deploy to Heroku:
  stage: deploy
  image: ruby:latest
  only:
    refs:
      - master
  script:
    - bash ./gitlab_deploy.sh