stages:
  - build
  - test

variables: 
  MYSQL_DATABASE: dev
  MYSQL_ROOT_PASSWORD: dev
  Host: mysql
  User: notroot
  Password: notrootdev
  Database: sushidb

all_tests: 
  stage: test 
  script: bash ./gitlabtests.sh
  stage: build
  script: bash ./gitlabdeploy.sh