image: python:latest

services:
  - mysql:latest

stages:
  - stage
  - test
  - deploy
  
variables: 
  MYSQL_DATABASE: nigirifalls_db
  MYSQL_ROOT_PASSWORD: dev
  DB_HOST: mysql
  DB_USERNAME: root

Code quality: 
  stage: test 
  script: 
    - bash ./gitlab_tests.sh