image: python:latest

services:
  - mysql:latest

stages:
  - test
  - deploy
  
variables: 
  MYSQL_DATABASE: dev
  MYSQL_ROOT_PASSWORD: dev
  Host: mysql
  User: notroot
  Password: notrootdev
  Database: sushidb

Code quality: 
  stage: test 
  script: 
    - bash ./gitlab_tests.sh