image: python:latest

services:
  - mariadb:latest

stages:
  - stage
  - test
  - deploy
  
variables: 
  MYSQL_DATABASE: nigirifalls_db
  MYSQL_ROOT_PASSWORD: dev

Code quality: 
  stage: test 
  script: 
    - bash ./gitlab_tests.sh