# Generated by Django 2.1.5 on 2019-02-21 12:47

from django.db import migrations, models
import takeaway.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=takeaway.models.get_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dish_type', models.CharField(choices=[('maki', 'Maki'), ('nigiri', 'Nigiri'), ('sashimi', 'Sashimi'), ('meny', 'Meny')], default='maki', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_customer', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('pickup_time', models.DateTimeField()),
                ('comment', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('motatt', 'Motatt'), ('prod', 'I produksjon'), ('klar', 'Klar for henting'), ('hentet', 'Hentet av kunde'), ('kansellert', 'Ordre ble kansellert')], default='motatt', max_length=10)),
                ('dishes', models.ManyToManyField(to='takeaway.Dish')),
            ],
        ),
    ]
