# Generated by Django 2.1.7 on 2019-03-28 18:37

from django.db import migrations, models
import nigirifalls.storage_backends
import takeaway.models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(storage=nigirifalls.storage_backends.MediaStorage(), upload_to=takeaway.models.get_image_path),
        ),
    ]
