# Generated by Django 2.1.7 on 2019-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0002_dish_allergy_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergy_info',
            field=models.CharField(choices=[('gluten', 'G'), ('shellfish', 'Sh'), ('egg', 'E'), ('fish', 'F'), ('peanuts', 'P'), ('soy', 'So'), ('milk', 'Mi'), ('nuts', 'N'), ('celery', 'C'), ('mustard', 'Mu'), ('sesame', 'Se'), ('sulphites', 'Su'), ('lupin', 'L'), ('molluscs', 'Mo')], default='fish', max_length=50),
        ),
    ]
