# Generated by Django 2.1.5 on 2019-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0002_auto_20190224_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pickup_time',
            field=models.DateTimeField(help_text='YYYY-MM-DD HH:mm'),
        ),
    ]
