# Generated by Django 2.1.5 on 2019-02-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0002_auto_20190213_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_class',
            new_name='dish_type',
        ),
    ]
