# Generated by Django 2.1.7 on 2019-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0003_auto_20190213_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(choices=[('maki', 'Maki'), ('nigiri', 'Nigiri'), ('sashimi', 'Sashimi'), ('meny', 'Meny')], default='maki', max_length=7),
        ),
    ]
