# Generated by Django 2.1.7 on 2019-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0003_auto_20190313_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gluten', 'G'), ('shellfish', 'Sh'), ('egg', 'E'), ('fish', 'F'), ('peanuts', 'P'), ('soy', 'So'), ('milk', 'Mi'), ('nuts', 'N'), ('celery', 'C'), ('mustard', 'Mu'), ('sesame', 'Se'), ('sulphites', 'Su'), ('lupin', 'L'), ('molluscs', 'Mo')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='allergy_info',
        ),
        migrations.AddField(
            model_name='dish',
            name='allergy_info',
            field=models.ManyToManyField(to='takeaway.Allergen'),
        ),
    ]
