# Generated by Django 2.1.7 on 2019-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0004_auto_20190219_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_key', models.IntegerField()),
                ('name_of_customer', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('pickup_time', models.IntegerField()),
                ('comment', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
