# Generated by Django 2.1.7 on 2019-03-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0004_auto_20190320_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(choices=[('none', ' '), ('gluten', 'G'), ('shellfish', 'Sh'), ('egg', 'E'), ('fish', 'F'), ('peanuts', 'P'), ('soy', 'So'), ('milk', 'Mi'), ('nuts', 'N'), ('celery', 'C'), ('mustard', 'Mu'), ('sesame', 'Se'), ('sulphites', 'Su'), ('lupin', 'L'), ('molluscs', 'Mo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='allergy_info',
            field=models.ManyToManyField(default='none', to='takeaway.Allergen'),
        ),
    ]
