# Generated by Django 2.1.7 on 2019-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0005_orderinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='foreign_key',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='foreign_key',
            field=models.ManyToManyField(to='takeaway.Dish'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pickup_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(choices=[('motatt', 'Motatt'), ('prod', 'I produksjon'), ('klar', 'Klar for henting'), ('hentet', 'Hentet av kunde'), ('kansellert', 'Ordre ble kansellert')], default='motatt', max_length=10),
        ),
    ]
